{
 "title": "Monitoring",
 "description": "Monitoring",
 "tags": [ "monitoring" ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"54.169.85.51:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"54.169.85.51:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{instance=\"54.169.85.51:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total{job=\"worker_monitoring\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Monitoring",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 16 },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"54.169.85.51:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}