- hosts: "{{ passed_in_hosts }}"
  tasks:
    - name: Copy SSH private key to remote machine
      copy:
        src: ~/.ssh/id_rsa
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: 0600

    - name: Copy SSH public key to authorized_keys
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: 0600
